#!/usr/bin/env python3
"""Lifts prop layers (books, sparkle bursts, wall slab) out of the traced action
poses in the checkpoint commit and writes ios/mockjuice/Views/MascotAccessories.swift.

Each prop's coordinates are re-based so its own top-left is (0, 0). Re-run with:
    python3 tools/mascot/extract_accessories.py
Source is read from git (SOURCE_REF), so it still works after the poses are removed.
"""
import re
import subprocess
import sys
from pathlib import Path

SOURCE_REF = "3f7844a"
SOURCE_PATH = "ios/mockjuice/Views/MascotSandbox.swift"
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "ios/mockjuice/Views/MascotAccessories.swift"

# (swift name, figure, layer indices in that figure's draw order, note)
SPECS = [
    ("books", "learning", [1, 6, 7, 8, 11, 15, 16, 19, 20, 21, 22, 23, 24, 25, 26, 27],
     "Blue and yellow book stack from the Learning pose."),
    ("sparkleBurstTwo", "jumping", [8, 9],
     "Two-stroke excitement burst from the Jumping pose."),
    ("sparkleBurstThree", "peeking", [5, 6, 8],
     "Three-stroke surprise burst from the Peeking pose."),
    ("wallSlab", "peeking", [1],
     "Wall edge from the Peeking pose. Its left edge is cut to the character's outline, so redraw it as a plain rounded rect if it needs to sit anywhere else."),
]

TOKEN = re.compile(r"[MLCZ]|-?\d+(?:\.\d+)?")
LAYER = re.compile(r'^\s*TracedLayer\((\.\w+), (\.\w+), "([^"]*)"(.*)\),\s*$')
GRADIENT = re.compile(r'gradient: \(([-\d.]+), ([-\d.]+), ([-\d.]+), ([-\d.]+), ("#\w+"), ("#\w+")\)')
BLUR = re.compile(r"blur: ([\d.]+)")


def fmt(v: float) -> str:
    s = f"{v:.1f}"
    return s[:-2] if s.endswith(".0") else s


def read_source() -> list[str]:
    return subprocess.check_output(
        ["git", "show", f"{SOURCE_REF}:{SOURCE_PATH}"], cwd=ROOT, text=True
    ).splitlines()


def figure_layers(lines: list[str], name: str) -> list[re.Match]:
    start = next(i for i, l in enumerate(lines) if l.strip().startswith(f"static let {name} = TracedFigure("))
    out = []
    for l in lines[start:]:
        if l.strip() == "])":
            break
        m = LAYER.match(l)
        if m:
            out.append(m)
    return out


def coords(path: str) -> list[tuple[float, float]]:
    nums = [float(t) for t in TOKEN.findall(path) if t not in "MLCZ"]
    return list(zip(nums[0::2], nums[1::2]))


def shift_path(path: str, dx: float, dy: float) -> str:
    out, buf = [], []

    def flush():
        for i in range(0, len(buf), 2):
            out.append(f"{fmt(buf[i] - dx)} {fmt(buf[i + 1] - dy)}")
        buf.clear()

    result = ""
    for t in TOKEN.findall(path):
        if t in "MLCZ":
            flush()
            result += (" ".join(out) if out else "") + t
            out.clear()
        else:
            buf.append(float(t))
    flush()
    result += " ".join(out)
    return result


def build(lines: list[str]) -> str:
    blocks = []
    for name, fig, picks, note in SPECS:
        layers = figure_layers(lines, fig)
        chosen = [layers[i] for i in picks]
        pts = [p for m in chosen for p in coords(m.group(3))]
        dx = min(x for x, _ in pts)
        dy = min(y for _, y in pts)
        w = max(x for x, _ in pts) - dx
        h = max(y for _, y in pts) - dy
        rows = []
        for m in chosen:
            ink, role, path, tail = m.groups()
            extra = ""
            b = BLUR.search(tail)
            if b:
                extra += f", blur: {b.group(1)}"
            g = GRADIENT.search(tail)
            if g:
                x1, y1, x2, y2 = (float(v) for v in g.groups()[:4])
                extra += (f", gradient: ({fmt(x1 - dx)}, {fmt(y1 - dy)}, {fmt(x2 - dx)}, "
                          f"{fmt(y2 - dy)}, {g.group(5)}, {g.group(6)})")
            rows.append(f'            TracedLayer({ink}, {role}, "{shift_path(path, dx, dy)}"{extra}),')
        blocks.append(
            f"    /// {note} About {w:.0f} x {h:.0f} px in sheet pixels; origin is the art's top-left.\n"
            f'    static let {name} = MascotPart(id: "{name}", anchor: .zero, layers: [\n'
            + "\n".join(rows) + "\n        ])\n"
        )
    return (
        "import SwiftUI\n\n"
        "// Props lifted from the traced sheet poses (generated by tools/mascot/extract_accessories.py).\n"
        "// Each is a MascotPart whose paths start at (0, 0); place and pivot it where it is used.\n\n"
        "enum MascotAccessories {\n" + "\n".join(blocks) + "}\n"
    )


if __name__ == "__main__":
    OUT.write_text(build(read_source()))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
    sys.exit(0)
